project-one/main/urls.py
from django.urls import path
from django.conf.urls import url
from main.view.views import index, submission, future, save_new_user_image, classify_image, delete_images, random_agent, train_agent_two, general_settings, train_agent_one

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    url(r'^submission', submission, name='submission'),
    url(r'^settings', general_settings, name='settings'),
    url(r'^future', future, name='future'),
    url(r'^save_new_user_image', save_new_user_image, name='save_new_user_image'),
    url(r'^classify_image', classify_image, name='classify_image'),
    url(r'^delete_images', delete_images, name='delete_images'),
    url(r'^random_agent', random_agent, name='random_agent'),
    url(r'^train_agent_one', train_agent_one, name='train_agent_one'),
    url(r'^train_agent_two', train_agent_two, name='train_agent_two'),
]

project-one/whatMemeAmI/urls.py
"""project-one URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls)
]

project-one/main/controller/forms/uploadImageForm.py
from django.forms import ModelForm
from django import forms
from main.model.models import UserImage


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserImage
        fields = ['name', 'image']

    def clean(self):
        name = self.cleaned_data['name']
        if UserImage.objects.filter(name=name):
            raise forms.ValidationError("this image name ist already taken, please choose another name")

project-one/main/view/templates/components/classify_image.html
<div class="flex-box-content box-card-style">
<form action="{% url 'main:classify_image' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Classify your Image</h3>
    <p>Choose the image for classification:</p>
    <div class="fieldWrapper" id="imageSelector">
        {% if image_names|length != 0 %}
            <select name="imageNames" size="1">
                {% for name in image_names %}
                    <option value={{ name }}>{{ name }}</option>
                {% endfor %}
            </select>
        {% else %}
            Upload an image first.
        {%endif%}
    </div>
    <button type="submit" name="button" value="agent_one">Agent RMSprop classification</button>
    <button type="submit" name="button" value="agent_two">Agent Adam classification</button>
</form>
</div>

project-one/main/view/templates/components/classify_result.html
<div id="classify-results-container">
 {% load static %}
    {% if predicted_class and max_percentage %}

    <h3>Your Result</h3>
    <h4>{{ max_percentage }}% similarity with <strong> {{ predicted_class }} </strong></h4>
    <div class="predictions">
        <img class="classified-images" src="{{ user_image }}">
        {% if heatmap_path%}
           <img class="classified-images" src="{{ heatmap_path }}">
        {% endif %}
           <img class="classified-images" src="{% static predicted_class_image_path %}">
        {% endif %}
    </div>
    {% if second_predicted_class and second_percentage %}
    <h4>other similarities:
    <p> {{ second_percentage }}% with <strong>{{ second_predicted_class }}</strong></p></h4>
    <div class="more-predictions">
         <img src="{% static second_predicted_class_image_path %}">
    </div>
    {% endif %}
</div>

project-one/main/view/templates/components/delete_images.html
<form action="{% url 'main:delete_images' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <h3>Uploaded Images</h3>
        <ul id="uploaded-images-list">
        {% for name in image_names%}
        <li>
            <input class="checkbox" type="checkbox" name="deleteImageBox" value="{{ name }}">
            <label>{{ name }}</label>
        </li>
        {% endfor %}
        </ul>
        <button class="delete" type="submit">Delete</button>
    </div>
    <br>
</form>

project-one/main/view/templates/components/header.html
<nav>
    <a href="{% url 'main:index' %}">Homepage</a>
    <a href="{% url 'main:future' %}">What Meme Am I?</a>
    <a href="{% url 'main:settings' %}">Settings</a>
</nav>

project-one/main/view/templates/components/random_agent.html
<div>
    <form action="{% url 'main:random_agent' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load static %}

        <h3> Test Random Agent</h3>
        <div class="fieldWrapper">
           <p> The Random Agent takes one random image from the testing-database and "classifies" it by taking a random category <br>and claiming the image belongs in this category.<br>The percentage number helps the Random Agent acting as if he knows what he does.</p>
            <div class="tooltip">Random Seed
                <span class="tooltiptext">The random seed lets you recreate a classification.<br>If you "Classify" with seed "1" you will always see the same result for seed "1".</span></div>:
            <input type="number" name="randomSeed" placeholder="1">
        </div>
        <br>
        <button type="submit" name="button" value="random_agent">"Classify"</button>
    </form>
</div>
<div>
    <p>
        <div>
            {% if image_label and guess_label and percentage %}
            The Agent is {{percentage}}% certain.
            <div id="left">
                <p>Your "uploaded" picture.</p>
                <img src="{% static img_classified %}" class="responsive">
                 <p class="subtitle">{{image_label}}</p>
            </div>
            <div id="right">
                <p>The class the Agent assigned your picture to.</p>
                <img src="{% static img_class_predicted %}" class="responsive">
                <p class="subtitle">{{guess_label}}</p>
            </div>
            {% endif %}
        </div>
    </p>
</div>

project-one/main/view/templates/components/statistics.html
<div id="statistics-container">
    {% load static %}
    <h3>Statistics of the agents</h3>
    <ul data-header="Erklärung">
        <li>Train loss: Training loss is the error on the training set of data</li>
        <li>Val loss: Validation loss is the error after running the validation set of data through the trained network</li>
        <li>Train acc: The accuracy of a agent on examples it has seen while training</li>
        <li>Val acc: The accuracy of the agent from images that is has not seen while training</li>
    </ul>
    <div class="flex-box-container">
        <div class="flex-box-content box-card-style">
            <h4>Agent with 'RMSprop' optimizer</h4>
            <img src="{% static '/images/RMSprop_agent_plot.png' %}">
        </div>
        <div class="flex-box-content box-card-style">
            <h4>Agent with 'Adam' optimizer</h4>
            <img src="{% static '/images/Adam_agent_plot.png' %}">
        </div>
    </div>
</div>

project-one/main/view/templates/components/train_agent_one.html
<div class="flex-box-content box-card-style">
<h3>Training - agent with 'RMSProp' optimizer</h3>
<form action="{% url 'main:train_agent_one' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="random-seed-field">
      <label>Random Seed:</label>
      <input type="number" name="randomSeedTrainAgentOne" placeholder="default = 1">
    </div>
    <button type="submit" name="button">Training</button>
</form>
</div>

project-one/main/view/templates/components/train_agent_two.html
<div class="flex-box-content box-card-style">
<h3>Training - agent with 'Adam' optimizer</h3>
<form action="{% url 'main:train_agent_two' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="random-seed-field">
        <label>Random Seed:</label>
        <input type="number" name="randomSeedTrainAgentTwo" placeholder="default = 1">
    </div>
    <button type="submit" name="button">Training</button>
</form>
</div>

project-one/main/view/templates/components/upload_image_form.html
<div class="flex-box-content box-card-style">
<form action="{% url 'main:save_new_user_image' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Upload your images</h3>
    {{ upload_image_form.non_field_errors }}
    <div class="fieldWrapper">
        <label>Image name:</label>
        {{ upload_image_form.name }}
    </div>
    <div class="fieldWrapper">
        <label>Image:</label>
        {{ upload_image_form.image }}
    </div>
    <button type="submit" value="Upload">Upload</button>
</form>
</div>